"""empty message

Revision ID: 89d726307515
Revises: 
Create Date: 2017-03-20 21:02:11.159150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d726307515'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=12), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.String(length=30), nullable=True),
    sa.Column('pic_ex', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
